In [1]:
#imports
import torch
import pandas as pd
import time

In [2]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/MyDrive/598-DLH/mimic
# %ls

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive/MyDrive/598-DLH/mimic

In [3]:
# import pandas as pd
# READ_PROPORTION = 20
# READ_PROPORTION_FOR_NOTES = 20
# READ_PROPORTION_FOR_CHARTEVENT = 15
# ad = pd.read_csv('ADMISSIONS.csv.gz', nrows=58976 // READ_PROPORTION, compression='gzip')
# chart = pd.read_csv('CHARTEVENTS.csv.gz', nrows=330712483 // READ_PROPORTION_FOR_CHARTEVENT, compression='gzip')
# patients = pd.read_csv('PATIENTS.csv.gz', nrows=46520 // READ_PROPORTION, compression='gzip')
# notes = pd.read_csv('NOTEEVENTS.csv.gz', nrows=2083180 // READ_PROPORTION_FOR_NOTES, compression='gzip') #only 1619465 has charttime
# icu = pd.read_csv('ICUSTAYS.csv.gz', nrows=61532 // READ_PROPORTION, compression='gzip')
# diagnoses = pd.read_csv('DIAGNOSES_ICD.csv.gz', nrows=651047 // READ_PROPORTION, compression='gzip')
# Dictionary table should be loaded entirely
# d_items = pd.read_csv('D_ITEMS.csv.gz', nrows=12487 // 1, compression='gzip') 
# d_icd_diag = pd.read_csv('D_ICD_DIAGNOSES.csv.gz', nrows=14710 // 1, compression='gzip')

In [4]:
features = [211, 220045, 220277, 676, 223762, 51, 220050, 53, 8368, 220051, 618, 220210, 1817, 228640, \
            74, 224828, 812, 3420, 2981, 7459, 6003, 778, 834, 770, 220587, 1162, 5876, 225624, 3728, 225612, \
            1523, 1525, 220615, 4948, 225651, 1529, 220621, 1531, 225668, 1532, 220635, 4381, 225925, 1535, 227442, \
            225690, 851, 227429, 3761, 220545, 814, 220228, 1533, 227466, 1542, 220546, 1528, 227468, 828, 225170]

In [5]:
# 330 712 483//15
# 0-22M
# 22M-44M
batch_size = 22000000
skip = [i*batch_size for i in range(15)]
skip
colnames = pd.read_csv('CHARTEVENTS.csv.gz', nrows=1, compression='gzip').columns

In [6]:
# i=10

for i in range(10, 15):

  batch = pd.read_csv('CHARTEVENTS.csv.gz', nrows=batch_size, skiprows=skip[i], names=colnames, compression='gzip')

  features_in_chart = []

  itemids = batch['ITEMID'].values

  for feat in features:
    if feat in itemids:
      features_in_chart.append(feat)

  # len(features_in_chart)

  with open('features_in_chart_'+str(i)+'.txt', 'w') as f:
    for item in features_in_chart:
        f.write("%s\n" % item)

  del batch

  reset in out

  time.sleep(30)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (8,10,14) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [19]:
feature_set = set()

for i in range(12):
  print(f'File {i}')
  with open('features_in_chart_'+str(i)+'.txt', 'r') as f:
    for line in f:
      feature = int(line)
      feature_set.add(feature)
  #   print(feature)
  # print()

File 0
File 1
File 2
File 3
File 4
File 5
File 6
File 7
File 8
File 9
File 10
File 11

In [21]:
len(feature_set)

57

In [23]:
set(features).difference(feature_set)

{225170, 225925, 228640}

In [11]:
test = pd.read_csv('CHARTEVENTS.csv.gz', nrows=10000, skiprows=skip[9], names=colnames, compression='gzip')

In [13]:
test[test['ITEMID'].isin(features)]

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,ITEMID,CHARTTIME,STORETIME,CGID,VALUE,VALUENUM,VALUEUOM,WARNING,ERROR,RESULTSTATUS,STOPPED
18,198034151,4754,109161,290261,51,2140-09-30 00:00:00,2140-09-30 00:46:00,21570,142,142.0,mmHg,NaN,NaN,NaN,NotStopd
20,198034153,4754,109161,290261,51,2140-09-30 01:00:00,2140-09-30 01:17:00,21570,138,138.0,mmHg,NaN,NaN,NaN,NotStopd
22,198034155,4754,109161,290261,51,2140-09-30 01:30:00,2140-09-30 02:17:00,21570,142,142.0,mmHg,NaN,NaN,NaN,NotStopd
25,198034158,4754,109161,290261,51,2140-09-30 01:45:00,2140-09-30 02:17:00,21570,142,142.0,mmHg,NaN,NaN,NaN,NotStopd
26,198034159,4754,109161,290261,51,2140-09-30 02:00:00,2140-09-30 03:13:00,21570,131,131.0,mmHg,NaN,NaN,NaN,NotStopd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9790,197709455,4439,173038,212721,51,2172-06-18 09:00:00,2172-06-18 09:16:00,14418,143,143.0,mmHg,NaN,NaN,NaN,NotStopd
9803,197709468,4439,173038,212721,51,2172-06-18 09:30:00,2172-06-18 09:36:00,14418,132,132.0,mmHg,NaN,NaN,NaN,NotStopd
9805,197709470,4439,173038,212721,51,2172-06-18 10:00:00,2172-06-18 10:48:00,14418,137,137.0,mmHg,NaN,NaN,NaN,NotStopd
9815,197709480,4439,173038,212721,51,2172-06-18 10:30:00,2172-06-18 10:48:00,14418,133,133.0,mmHg,NaN,NaN,NaN,NotStopd
9816,197709481,4439,173038,212721,51,2172-06-18 11:00:00,2172-06-18 11:49:00,14418,133,133.0,mmHg,NaN,NaN,NaN,NotStopd